version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=1234
      - AUTH_TOKEN=lumadent-secret-token
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
